### ISSUE TITLE
The documented result of versioning strategies is irrelevant

### ISSUE THREAD

**Issue by stof** [mtarld/composer-vendor-scaper#1]
I haven't tried the tool, This is based purely on what is documented in the readme (so if the readme is wrong about how the tool behaves, that might be the actual issue).

I'm talking about that part:

```
 Choose a version strategy for symfony/console [fixed]:
  [0] fixed
  [1] patch
  [2] minor
  [3] major
 > patch

 Choose a version strategy for symfony/finder [fixed]:
  [0] fixed
  [1] patch
  [2] minor
  [3] major
 > minor

 Choose a version strategy for symfony/string [fixed]:
  [0] fixed
  [1] patch
  [2] minor
  [3] major
 > major

 Result
 ----------------- ---------- 
  Name              Version   
 ----------------- ---------- 
  symfony/console   ^5.2.0.0  
  symfony/finder    ^5.2.0    
  symfony/string    ^5.2      
 ----------------- ---------- 
```

all generated constraints are exactly the same. I think you confused the `~` and `^` operators.

**Comment by stof** [comment]
the `^` operators means "go from that version until the next semver-breaking version" (with semver-breaking versions being major versions plus the special semver behavior of 0.x where bumping `x` is then also treated like semver-breaking)

**Comment by mtarld** [comment]
Indeed, I misunderstood that.
Many thanks for reporting this issue (which made that tool unusable)
